name: Build solution
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Check if directory exists
        run: |
          ls -la ~/.nuget/packages
          if [ ! -d ~/.nuget/packages ]; then
            echo "Creating directory ~/.nuget/packages"
            mkdir -p ~/.nuget/packages
          fi
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install dependecies
        run: dotnet restore
      - name: Build
        run: dotnet build